# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(choices=[
                    ('PHP', 'Philippine Peso'),
                    ('USD', 'US Dollar'),
                    ('EUR', 'Euro'),
                    ('RSD', 'Serbian Dinar')
                ], default='PHP', max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('from_account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='from_account',
                    to='transactions.Account'
                )),
                ('to_account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='to_account',
                    to='transactions.Account'
                )),
            ],
        ),
    ]
